networks:
  front_back:

services:
  frontend:
    container_name: frontend
    build:
      context: ./frontend/
    ports:
      - "443:443"
    volumes:
      - ./frontend/static:/usr/share/nginx/html/
      - ./frontend/src/:/home/app/src/
    command: >
      sh -c "
      npm run watch &
      nginx -g 'daemon off;'"
    restart: always
    networks:
      - front_back
