networks:
  front_back:
  back_db:

services:
  frontend:
    container_name: frontend
    volumes:
      - ./frontend/src:/home/app/src
      - ./frontend/public:/home/app/static/public
      - static_files:/home/app/static
    build:
      context: ./frontend/
    ports:
      - 443:443
    env_file: .env
    restart: always
    depends_on:
      - backend
    networks:
      - front_back

  backend:
    container_name: backend
    build:
      context: ./backend/
    expose:
      - 8000
    env_file: .env
    restart: always
    depends_on:
      - db
    volumes:
      - ./backend/project:/usr/src/app
      - static_files:/usr/src/static
    networks:
      - front_back
      - back_db

  db:
    image: postgres:15
    container_name: postgresql
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - 5432:5432
    restart: always
    networks:
      - back_db
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  static_files:
  db_data:
