networks:
  front_back:
  back_db:

services:
  frontend:
    container_name: frontend
    volumes:
      - ./frontend/src:/home/app/src
      - ./frontend/public:/home/app/static/public
      - static_files:/home/app/static
    env_file: .env
    build:
      context: ./frontend/
    ports:
      - ${FRONTEND_PORT}:${FRONTEND_PORT}
    restart: always
    depends_on:
      - backend
    networks:
      - front_back

  backend:
    container_name: backend
    env_file: .env
    build:
      context: ./backend/
    expose:
      - ${BACKEND_PORT}
    restart: always
    depends_on:
      - db
    volumes:
      - ./backend/project:/usr/src/app
      - static_files:/usr/src/static
    networks:
      - front_back
      - back_db

  db:
    image: postgres:15
    container_name: postgresql
    env_file: .env
    ports:
      - ${DATABASE_PORT}:${DATABASE_PORT}
    restart: always
    networks:
      - back_db
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  static_files:
  db_data:
